-- conexao com o flyway
-- flyway inativo
--criei a tabela manualmente

CREATE SEQUENCE SEQ_USUARIOS
    START WITH 1
    INCREMENT BY 1 NOCACHE
       NOCYCLE;

CREATE TABLE TBL_USUARIOS
(
    USUARIO_ID INTEGER DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL PRIMARY KEY,
    NOME       VARCHAR2(100 CHAR) NOT NULL,
    EMAIL      VARCHAR2(100 CHAR)  NOT NULL,
    SENHA      VARCHAR2(20 CHAR)   NOT NULL
);